<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ashani Jayasekera">
<meta name="dcterms.date" content="2024-11-20">

<title>FinalProjectPaper</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="FinalProject_files/libs/clipboard/clipboard.min.js"></script>
<script src="FinalProject_files/libs/quarto-html/quarto.js"></script>
<script src="FinalProject_files/libs/quarto-html/popper.min.js"></script>
<script src="FinalProject_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="FinalProject_files/libs/quarto-html/anchor.min.js"></script>
<link href="FinalProject_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="FinalProject_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="FinalProject_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="FinalProject_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="FinalProject_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">FinalProjectPaper</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ashani Jayasekera </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 20, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<section id="topic" class="level2">
<h2 class="anchored" data-anchor-id="topic">1.1 Topic</h2>
<p>This project analyzes the usage of the <a href="https://data.austintexas.gov/widgets/tyfh-5r8s?mobile_redirect=true">Austin Metro BikeShare</a>, the bike-sharing program of Austin, TX. There are 3 main inquiries of focus:</p>
<ol type="1">
<li><p>The distribution of bike stations across the city of Austin and their capacity.</p></li>
<li><p>The usage of Austin BikeShare and whether the usage is dependent on the month in the year and whether it changes across years.</p></li>
<li><p>The usage of the bikesharing system across user types.</p></li>
</ol>
<p>Austin, TX is currently expanding their bikeshare program with a <a href="https://www.kxan.com/news/local/austin/capmetro-rolling-out-21m-metrobike-expansion-plan/">$21 million investment</a>. Using these inquires, city developers can determine where area where new docking stations are needed and where there is no existing stations. Furthermore, city officials can understand their user demographic (subscribers or single user) better and when during the year bikes are used more than others.</p>
</section>
<section id="source-of-data" class="level2">
<h2 class="anchored" data-anchor-id="source-of-data">1.2 Source of Data</h2>
<p>The data used for this project is “<a href="https://console.cloud.google.com/marketplace/browse?filter=solution-type:dataset&amp;inv=1&amp;invt=AbiAsg">Austin Bikeshare</a>”, a public database from Austin, TX hosted on Google BigQuery. There are two 2 tables in this dataset: “bikeshare_stations,” which includes the locations and the number of bikes that can be docked at a given station of the 82 active bike stations, and “bikeshare_trips,” which include data from 2.27 million bike trips taken from 2013 to 2024. The trip date including the start and end times, duration, start and end stations, and the user type are the variables that are used in this study.</p>
</section>
<section id="github-repository-packages-maps" class="level2">
<h2 class="anchored" data-anchor-id="github-repository-packages-maps">1.3 Github Repository, Packages, maps</h2>
<p>The link to the GitHub repository is: https://github.com/ashanijay/SURV727.</p>
<p>The main R packages used in this study are <code>DBI</code>, <code>ggplot</code>, <code>ggmap</code>, and <code>dbplyr.</code> Stadia Maps is used for map visualizations.</p>
</section>
</section>
<section id="analysis" class="level1">
<h1>2. Analysis</h1>
<section id="bike-station-analysis" class="level2">
<h2 class="anchored" data-anchor-id="bike-station-analysis">2.1 Bike Station analysis</h2>
<p>To begin,the data is accessed via a connection to BigQuery using <code>DBI</code>’s <code>dbConnect</code> function.</p>
<p>The number of bike stations that are active in the city of Austin are identified. This is defined as I first checked how many working bike stations there are, defined as stations that have a non-zero number of bikes and are available for renting and returning bikes.</p>
<div class="cell tbl-cap-location-bottom">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Number of active, working bike stations</caption>
<thead>
<tr class="header">
<th style="text-align: right;">f0_</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">82</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>There are 82 working bike stations currently. The proposed exapansion in the city of Austin will add an additional 1000 bike stations.</p>
<p>These bike stations are visualized below using <code>ggmap</code>.</p>
<p>From Figure 1, we can see that as of 2019, bike stations are mainly in downtown Austin. They are also some stations in Zilker Park and the UT Austin campus. There is one in the far West part of the city and a couple in the far East part of the city.</p>
<p>Most bike stations have a capacity of 13 or fewer bikes. These are the purple stations in the map. The orange stations are those that have 15 or bikes at the station. There are more of these in the north part of the city in “The Drag.”</p>
<p>The mean number of bikes per station is 13.46, and the median is 13, suggesting again that most bike stations are small with exception of a few larger stations where the number of bikes is closer to 20.</p>
</section>
<section id="analyzing-the-number-of-trips-taken-across-years-and-months" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-the-number-of-trips-taken-across-years-and-months">2.2 Analyzing the number of trips taken across years and months</h2>
<p>Next, the number of bike trips taken by month and by year are analyzed. Figure 2 below shows the result.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="FinalProject_files/figure-html/bike_trip_year_month_usage-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Number of bike trips by year and month</figcaption>
</figure>
</div>
</div>
</div>
<p>There are three things that are of note from Figure 2.</p>
<ol type="1">
<li><p>2019 and 2020 had the lowest number of trips. A possible reason for this could be the COVID-19 pandemic where individuals were not going to work and not traveling.</p></li>
<li><p>The number of trips increased year by year from 2013 to 2018. 2021-2023 there is another increase in the number of trips post the COVID-19 pandemic. The reason is likely twofold: over time more people started to know and use the shared bikes, and the bike program continued to expand their coverage and capacity, attracting more new users.</p></li>
<li><p>There is an apparent seasonal difference in terms of number of trips. There are two peaks. Once between February and May and another between September and November. This is when there are more moderate temperatures in Austin. It is very warm in the summer and in the winter, it may be too cold to bike.</p></li>
</ol>
</section>
<section id="analyzing-the-time-taken-number-of-trips-taken-across-years-and-months" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-the-time-taken-number-of-trips-taken-across-years-and-months">2.3 Analyzing the time taken number of trips taken across years and months</h2>
<p>Another factor to look at is the duration of trips. Figure 3 and Figure 4 below show the average trip duration (in minute) by year and by month.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="FinalProject_files/figure-html/trip_duration_by_year-1.png" class="img-fluid figure-img" width="384"></p>
<figcaption>Trip duration by year</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="FinalProject_files/figure-html/trip_duration_by_month-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Trip duration by month</figcaption>
</figure>
</div>
</div>
</div>
<p>From Figure 3 and Figure 4, we can two things:</p>
<ol type="1">
<li><p>The average trip duration decreased over the yearsfrom 2013 to 2015 and then held fairly steady until 2019. When we were in the COVID-19 pandemic, the duration of the trips increased dramatically, nearly double that of 2018. (Note: 2024 is missing the last month and a half of the year as we are still in 2024. )</p></li>
<li><p>There is a slight seasonal difference in terms of trip duration. The summer months have longer average trip duration (31 -33 minutes per trip) compared to the rest of the year save for the month of December (25-30 minutes per trip).</p></li>
</ol>
</section>
<section id="bike-trip-analysis-user-types" class="level2">
<h2 class="anchored" data-anchor-id="bike-trip-analysis-user-types">2.4 Bike trip analysis – user types</h2>
<p>Besides year and month, another interesting variable is whether the bike trip is made by a “subscriber”, who holds an annual, monthly, or a student ridership plan, or a “single user”, a person who either uses a day pass, a weekend pass, or a single trip ticket. There are 74 classifications of riders in this data. Using descriptions of the <a href="https://www.mountbonnell.info/getting-around-austin/b-cycle-austin">different riders</a> the 74 classifications were collapsed into these two groups.</p>
<p>From the queried result above, we can see differences among subscribers and single users (and weekender) customers in terms of their bike usage. First, subscribers took fewer bike trips than customers – about 1.5 times more. Second, the trips taken by single users on average were around 34.8 minutes, while the trips taken by subscribers were much shorter on average 20 minutes; the difference in the average trip duration is around 15 mintues.</p>
<p>These differences are likely associated with the different purposes of trips: subscribers likely use the trip for commuting or short-distance connecting, while the customers are more likely to be tourists or occasional users who bought a day pass or single ride pass and used the bike to go around the city, and hence the longer trip duration.</p>
</section>
<section id="popular-bike-routes" class="level2">
<h2 class="anchored" data-anchor-id="popular-bike-routes">2.4 Popular Bike Routes</h2>
<p>Next, I analyzed the popular shared bike “routes”, defined as different combinations of a start station (where the bike was rented) and an end station (where the bike was returned). Below is the result of the top 20 most popular routes, their number of trips and average trip duration.</p>
<div class="cell tbl-cap-location-bottom">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Most popular bike routes</caption>
<thead>
<tr class="header">
<th style="text-align: left;">route</th>
<th style="text-align: right;">num_trips</th>
<th style="text-align: right;">duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3795 to 3798</td>
<td style="text-align: right;">25891</td>
<td style="text-align: right;">9.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">3798 to 3795</td>
<td style="text-align: right;">23796</td>
<td style="text-align: right;">13.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3798 to 3798</td>
<td style="text-align: right;">19850</td>
<td style="text-align: right;">28.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">2575 to 2575</td>
<td style="text-align: right;">18290</td>
<td style="text-align: right;">53.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3838 to 3798</td>
<td style="text-align: right;">16477</td>
<td style="text-align: right;">13.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2574 to 2574</td>
<td style="text-align: right;">15430</td>
<td style="text-align: right;">57.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2707 to 2707</td>
<td style="text-align: right;">14919</td>
<td style="text-align: right;">60.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">3798 to 2498</td>
<td style="text-align: right;">14592</td>
<td style="text-align: right;">7.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3798 to 2547</td>
<td style="text-align: right;">13578</td>
<td style="text-align: right;">8.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">3798 to 3838</td>
<td style="text-align: right;">13455</td>
<td style="text-align: right;">20.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: left;">route</th>
<th style="text-align: right;">num_trips</th>
<th style="text-align: right;">duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Dean Keeton/Whitis to 21st/Speedway @ PCL</td>
<td style="text-align: right;">17672</td>
<td style="text-align: right;">8.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">21st/Speedway @ PCL to Dean Keeton/Speedway</td>
<td style="text-align: right;">16301</td>
<td style="text-align: right;">7.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">21st/Speedway @ PCL to Dean Keeton/Whitis</td>
<td style="text-align: right;">16116</td>
<td style="text-align: right;">12.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zilker Park to Zilker Park</td>
<td style="text-align: right;">14753</td>
<td style="text-align: right;">58.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dean Keeton/Speedway to 21st/Speedway @ PCL</td>
<td style="text-align: right;">14504</td>
<td style="text-align: right;">7.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">21st &amp; Speedway <span class="citation" data-cites="PCL">@PCL</span> to Dean Keeton &amp; Speedway</td>
<td style="text-align: right;">14235</td>
<td style="text-align: right;">10.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dean Keeton &amp; Speedway to 21st &amp; Speedway <span class="citation" data-cites="PCL">@PCL</span></td>
<td style="text-align: right;">13543</td>
<td style="text-align: right;">10.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">26th/Nueces to 21st/Speedway @ PCL</td>
<td style="text-align: right;">12179</td>
<td style="text-align: right;">11.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Riverside/South Lamar to Riverside/South Lamar</td>
<td style="text-align: right;">9764</td>
<td style="text-align: right;">52.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">21st/Speedway @ PCL to 21st/Guadalupe</td>
<td style="text-align: right;">9762</td>
<td style="text-align: right;">8.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From the table, we can see that:</p>
<ul>
<li><p>There are some “routes” that share the same start station and end station. The fourth most popular routes is this type of route.</p></li>
<li><p>For routes that have different start and end stations, the most popular route is “Dean Keeton/Whitis to 21st/Speedway @ PCL”, which was taken 17672 times and for on average 8.4 minutes.</p></li>
<li><p>The next two popular routes with different start and end stations are quite similar. Both start from 21st/Speedway @ PCL, and end at Dean Keeton/Speedway or Dean Keeton/Whitis. These 2 routes have a volume of 16301 times and 16116 times, and the average duration is 7.4 minutes and 12.7 minutes respectivlly.</p></li>
</ul>
<p>However, when looking at popular routes taken by different types of users, we see very different patterns among subscribers and customers.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="FinalProject_files/figure-html/top_routes_by_subscriber-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Most popular bike routes taken by subscribers</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="FinalProject_files/figure-html/top_routes_by_customer-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Most popular bike routes taken by customers</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="need-to-update-these-sections" class="level2">
<h2 class="anchored" data-anchor-id="need-to-update-these-sections">Need to update these sections</h2>
<p>We can see that:</p>
<ul>
<li><p>Subscribers did short trips from one location to another, while customers tended to rent and return the bike at the same station.</p></li>
<li><p>The most popular routes taken by subscribers are all in Midtown Manhattan and are all short routes. I looked up the average trip duration for those routes and most of them are within 5-10 minutes.</p></li>
<li><p>On the other hand, customers liked to rent and return bikes at stations around Central Park and Broadway, and the duration on average lasted for half an hour to an hour, much longer than those routes taken by the subscribers.</p></li>
</ul>
</section>
</section>
<section id="conclusion" class="level1">
<h1>3. Conclusion</h1>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">3.1 Summary</h2>
<p>This project analyzes the usage of NYC bikeshare program from 2013 to 2018, focusing on the distribution of bike stations and their capacity, the number of trips and average trip duration, and the popular bike routes for different types of users. Visualizations are presented to help the reader grasp the information.</p>
<p>In conclusion:</p>
<ul>
<li><p>The number of bike trips and the average trip duration gradually increased year by year, suggesting that the program is growing and people in NYC are using the bikes more and more.</p></li>
<li><p>There are seasonal differences in terms of number of bike trips and trip duration. Both numbers are lower for the winter months than for the summer months.</p></li>
<li><p>Different types of users show very different shared bike riding behavior. The subscribers (who bought the annual ridership plan) did a lot of short trips, on average for 13 minutes. The most popular routes for subscribers are all 5-10 minute short routes in Midtown Manhattan. On the other hand, customers (who bought a single trip or day pass) did fewer trips than subscribers, but the average trip duration is about an hour. Customers tended to rent and return the bike at the same station. Stations around Central Park were the most popular for them.</p></li>
</ul>
</section>
<section id="limitation" class="level2">
<h2 class="anchored" data-anchor-id="limitation">3.2 Limitation</h2>
<p>There are a few limitations of the dataset and analysis:</p>
<ul>
<li><p>The bike station data does not include the time when the station was built, and does not include stations that were built after 2018. If such data was included, I would be able to look at the expansion of the bike station coverage and its relationship to bike usage, to see if there were interesting patterns to uncover.</p></li>
<li><p>The bike trip data does not specify which user had taken a trip, only that the trip was taken by a certain type of user. This is reasonable for confidentiality reasons. The limitation is that the unit of analysis can only be “trips”, not “users”, and there is no way to distinguish whether the trips were made by a single user or different users. It would be interesting to see whether the analysis based on “users” would arrive at different conclusions from the analysis based on “trips”, if some sort of unidentifiable user data could be provided.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>